In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [4]:
abc = np.zeros(10)

In [5]:
abc

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
ones_array = np.ones(3)
ones_array

array([1., 1., 1.])

In [7]:
identify_matrix = np.eye(5)
identify_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
range_array = np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [11]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [12]:
np.random.rand(2,2)

array([[0.7419714 , 0.1720149 ],
       [0.94470002, 0.40551963]])

In [13]:
np.random.randn(2,4)

array([[ 0.40776091, -0.27933355,  0.92047407,  0.15695156],
       [ 0.6311964 ,  0.06576706,  1.48354061, -0.13325354]])

In [15]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_array = np.array(my_list)
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
my_array[1][3:]

array([ 9, 10])

In [17]:
my_array[0][3]


4

In [18]:
my_array[1][3]

9

In [19]:
my_array.shape

(2, 5)

In [20]:
my_array.dtype

dtype('int32')

In [23]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
sum_array = array1 + array2
sum_array

array([5, 7, 9])

In [24]:
product_array = array1 * array2
product_array

array([ 4, 10, 18])

In [25]:
my_list = [1,2,3,4,5,6]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5, 6])

In [26]:
reshaped_array = my_array.reshape(2,3)

In [27]:
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [30]:
stacked_vertically = np.vstack((array1,array2))
stacked_vertically

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
stacked_horizontally = np.hstack((array1,array2))
stacked_horizontally

array([1, 2, 3, 4, 5, 6])

In [36]:
orignal_array = np.array([3,1,2,4,5])
sorted_array = np.sort(orignal_array)

In [37]:
sorted_array

array([1, 2, 3, 4, 5])

In [38]:
descending_array = np.sort(orignal_array)[::-1]

In [39]:
descending_array

array([5, 4, 3, 2, 1])

In [42]:
orignal_2d_array = np.array([[3,1,12],[6,5,4]])
sorted_by_rows = np.sort(orignal_2d_array,axis = 0)[::-1]

In [41]:
sorted_by_rows


array([[ 3,  1,  4],
       [ 6,  5, 12]])

In [43]:
sorted_by_rows

array([[ 6,  5, 12],
       [ 3,  1,  4]])

In [44]:
orignal_2d_array

array([[ 3,  1, 12],
       [ 6,  5,  4]])

In [45]:
sorted_by_rows = np.sort(orignal_2d_array,axis = 1)

In [46]:
sorted_by_rows


array([[ 1,  3, 12],
       [ 4,  5,  6]])

In [47]:
data = np.array([1,2,3,4,5],)
condition = data > 2
filtered_array = data[condition]

In [48]:
filtered_array

array([3, 4, 5])

In [50]:
data = np.array([1,2,3,4,5],)
condition = (data > 2) & (data > 5)
filtered_array = data[condition]

In [51]:
filtered_array

array([], dtype=int32)

In [52]:
data = np.array([0,12,1,4,5])
indices = np.where(data > 2)
filtered_values = data[indices]

In [53]:
filtered_values

array([12,  4,  5])

In [54]:
indices


(array([1, 3, 4], dtype=int64),)

In [55]:
data = np.array([1,2,3,4,5])
condition = data > 2
filtered_array = np.extract(condition,data)

In [56]:
filtered_array

array([3, 4, 5])

In [57]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [58]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
condition = np.sum(data,axis=1) > 10
filtered_data = data[condition]

In [60]:
filtered_data

array([[4, 5, 6],
       [7, 8, 9]])

In [61]:
column_means = np.mean(data,axis = 0)

In [62]:
column_means

array([4., 5., 6.])

In [63]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
data.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])